# Generated by Django 5.2.16 on 2026-07-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='feeding_notes',
            field=models.TextField(),
        ),
    ]
